# Generated by Django 4.1.2 on 2023-04-09 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("modelsapp", "0003_generatedquestion_delete_savedquestions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedquestion",
            name="date_created",
        ),
        migrations.RemoveField(
            model_name="generatedquestion",
            name="user",
        ),
        migrations.AlterField(
            model_name="generatedquestion",
            name="question_text",
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name="GeneratedQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="generatedquestion",
            name="question_set",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="modelsapp.generatedquestionset",
            ),
        ),
    ]
